"""empty message

Revision ID: 473ccc5292b9
Revises: b7cb4db9bd7e
Create Date: 2020-12-28 16:10:34.148827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473ccc5292b9'
down_revision = 'b7cb4db9bd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_code_key', 'project', type_='unique')
    op.drop_column('project', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('project_code_key', 'project', ['code'])
    # ### end Alembic commands ###
