"""empty message

Revision ID: d87a66846686
Revises: 473ccc5292b9
Create Date: 2020-12-28 16:13:33.342556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87a66846686'
down_revision = '473ccc5292b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'project', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'code')
    # ### end Alembic commands ###
